apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: clio1-topology-updater
  labels:
    k8s-app: clio1-topology-updater
spec:
  selector:
    matchLabels:
      name: clio1-topology-updater
  template:
    metadata:
      labels:
        name: clio1-topology-updater
    spec:
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "testnet"
          effect: "PreferNoSchedule"
      containers:
      - name: crond
        command: ["bash", "-c", "while true; do bash /configmap/topology-updater; sleep 3600; done"]
        env:
        - name: BASE_URL
          value: "https://api.clio.one/htopology/v1"
        - name: CNODE_PORT
          value: "31337"
        - name: CNODE_HOSTNAME
          value: "relay.iohk-tn.cardano.none.guru"
        - name: CNODE_VALENCY
          value: "1"
        - name: TESTNET_MAGIC
          value: "1097911063"
        image: rcmorano/ubuntu-crond:latest
        imagePullPolicy: "Always"
        resources:
          limits:
            cpu: 50m
            memory: 50Mi
          requests:
            cpu: 50m
            memory: 50Mi
        volumeMounts:
        - mountPath: /etc/profile.d
          name: docker-environment
        - mountPath: /configmap
          name: clio1-topology-updater
      volumes:
      - name: docker-environment
        emptyDir:
          medium: Memory
      - name: clio1-topology-updater
        configMap:
          name: clio1-topology-updater
